name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - "1.70"
          - "stable"
          - "beta"
          - "nightly"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
